apiVersion: v1
kind: Service
metadata:
  name: petstore-v1
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: petstore
    version: v1
---
apiVersion: v1
kind: Service
metadata:
  name: petstore-v2
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: petstore
    version: v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
      version: v1
  template:
    metadata:
      labels:
        app: petstore
        version: v1
    spec:
      containers:
      - image: swaggerapi/petstore
        imagePullPolicy: Always
        name: petstore
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
      version: v2
  template:
    metadata:
      labels:
        app: petstore
        version: v2
    spec:
      containers:
      - image: swaggerapi/petstore
        imagePullPolicy: Always
        name: petstore
        ports:
        - containerPort: 8080
          name: http