apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  labels:
    expose: "true"
  name: mgmt-argo-rt-80
  namespace: argocd
spec:
  hosts:
  - '*'
  http:
  - forwardTo:
      destinations:
      - port:
          number: 80
        ref:
          cluster: mgmt
          name: argocd-server
          namespace: argocd
    labels:
      waf: "true"
    name: argocd
  virtualGateways:
  - cluster: mgmt
    name: mgmt-north-south-gw-80
    namespace: istio-gateways
  workloadSelectors: []