apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-config
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/wildcard/v2-workshop/cluster1/2.1.b-routing-tls-single-upstream
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true