apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-trust
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/solo-io/gitops-library
    targetRevision: HEAD
    path: bookinfo/overlay/config/domain/wildcard/v2-workshop/mgmt/1.1.b-root-trust-secretref
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true