apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- base/rollouts-extension.yaml

components:
- github.com/argoproj-labs/argocd-extensions/manifests/?ref=main

namespace: argocd
  
images:
- name: quay.io/argoproj/argocd
  newTag: v2.4.6
  digest: sha256:a0a6f3974427c826140b020a483181626e1dcf7280ae6eae2bce48e1a13e7577

#images:
#- name: quay.io/argoproj/argocd
#  newName: ghcr.io/argoproj/argocd
#  newTag: 2.4.0-99a889cd

patchesJson6902:
- path: overlays/application-controller-status-processors.yaml
  target:
    group: apps
    kind: StatefulSet
    name: argocd-application-controller
    version: v1

patchesStrategicMerge:
- overlays/argocd-cm.yaml
