- {op: add,  path: /spec/template/spec/containers/0/command/-, value: --status-processors}
- {op: add,  path: /spec/template/spec/containers/0/command/-, value: "20"}
- {op: add,  path: /spec/template/spec/containers/0/command/-, value: --operation-processors}
- {op: add,  path: /spec/template/spec/containers/0/command/-, value: "10"}
- {op: add,  path: /spec/template/spec/containers/0/command/-, value: --repo-server-timeout-seconds}
- {op: add,  path: /spec/template/spec/containers/0/command/-, value: "180"}