apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: bank-lob-workspace-settings
  namespace: bank-demo
spec:
  exportTo:
  - resources:
    - kind: ALL
      labels:
        expose: "true"
    workspaces:
    - name: gateways
  importFrom:
  - resources:
    - kind: SERVICE
    workspaces:
    - name: gateways
  options:
    federation:
      enabled: true
      hostSuffix: global