apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: bank-lob
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: mgmt
    namespaces:
    - name: bank-demo